In [1]:
#1. Create a NumPy array of integers from 1 to 10 and print its shape, size, and data type.
import numpy as np
a=np.arange(1, 11)  # Creating an array of integers from 1 to 10
print("Shape:", a.shape)  # Printing the shape of the array
print("Size:", a.size)  # Printing the size of the array
print("Data Type:", a.dtype)  # Printing the data type of the array

Shape: (10,)
Size: 10
Data Type: int64


In [2]:
#2. Create a 2D NumPy array of shape (3, 3) with values from 1 to 9 and display:
#● Number of dimensions (ndim)
#● Shape
#● Sum of all elements
arr = np.arange(1, 10).reshape(3, 3)  # Creating a 2D array with values from 1 to 9
print("Number of Dimensions:", arr.ndim)  # Printing the number of dimensions
print("Shape:", arr.shape)  # Printing the shape of the array
print("Sum of all elements:", arr.sum())  # Printing the sum of all elements

Number of Dimensions: 2
Shape: (3, 3)
Sum of all elements: 45


In [3]:
#3. Create an array of 5 zeros and another of 5 ones. Multiply both and display the result.
zeros_array = np.zeros(5)  # Creating an array of 5 zeros
ones_array = np.ones(5)  # Creating an array of 5 ones
result = zeros_array * ones_array  # Multiplying both arrays
print("Result of multiplication:", result)  # Displaying the result

Result of multiplication: [0. 0. 0. 0. 0.]


In [4]:
#4. Create an array of even numbers between 20 and 40. Use slicing to display the first 3 elements.
even = np.arange(10,41,2)
print("Even numbers between 20 and 40:", even)  # Displaying the even numbers
print("First 3 elements:", even[:3])  # Displaying the first 3 elements

Even numbers between 20 and 40: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
First 3 elements: [10 12 14]


In [5]:
#5. Reshape a 1D array of 12 elements into a 3x4 matrix and calculate the sum along axis=0 and axis=1.
arr_1d = np.arange(12)  # Creating a 1D array of 12 elements
reshaped_matrix = arr_1d.reshape(3, 4)  # Reshaping into a 3x4 matrix
print("Reshaped Matrix:\n", reshaped_matrix)  # Displaying the reshaped matrix
print("Sum along axis=0:", reshaped_matrix.sum(axis=0))  # Sum along columns
print("Sum along axis=1:", reshaped_matrix.sum(axis=1))  # Sum along rows

Reshaped Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum along axis=0: [12 15 18 21]
Sum along axis=1: [ 6 22 38]


In [6]:
#6. Create a 5x5 identity matrix using NumPy.
identity_matrix = np.eye(5)  # Creating a 5x5 identity matrix
print("5x5 Identity Matrix:\n", identity_matrix)  # Displaying the identity matrix

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
#7. Create a 1D array of 10 random integers between 1 and 100. Find the maximum and minimum values and their indices.
random_array = np.random.randint(1, 101, size=10)  # Creating a 1D array of 10 random integers
print("Random Array:", random_array)  # Displaying the random array
max_value = random_array.max()  # Finding the maximum value
min_value = random_array.min()  # Finding the minimum value
print("Maximum Value:", max_value, "at index", random_array.argmax())  # Displaying max value and index
print("Minimum Value:", min_value, "at index", random_array.argmin())  # Displaying min value and index

Random Array: [91 94 31 90 75  8 73 47 99 24]
Maximum Value: 99 at index 8
Minimum Value: 8 at index 5


In [8]:
#8. Generate a NumPy array of 6 float numbers between 0 and 1 using linspace. Round the values to 2 decimal places.
float_array = np.linspace(0, 1, 6)  # Generating an array of 6 float numbers between 0 and 1
rounded_array = np.round(float_array, 2)  # Rounding the values to 2 decimal places
print("Array of float numbers between 0 and 1:", rounded_array)  # Displaying the rounded array

Array of float numbers between 0 and 1: [0.  0.2 0.4 0.6 0.8 1. ]


In [10]:
#9. Create a NumPy array with some repeated values and remove the duplicates.
repeated_array = np.array([1, 2, 2, 3, 4, 4, 5])  # Creating an array with repeated values
unique_array = np.unique(repeated_array)  # Removing duplicates
print("Original Array:", repeated_array)  # Displaying the original array
print("Array after removing duplicates:", unique_array)  # Displaying the array after removing duplicates

Original Array: [1 2 2 3 4 4 5]
Array after removing duplicates: [1 2 3 4 5]


In [11]:
#10. Create two 3x3 matrices and perform the following operations:
#● Matrix addition
#● Matrix multiplication
#● Element-wise multiplication
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # First 3x3 matrix
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])  # Second 3x3 matrix
print("Matrix A:\n", matrix_a)  # Displaying first matrix
print("Matrix B:\n", matrix_b)  # Displaying second matrix
print("Matrix Addition:\n", matrix_a + matrix_b)  # Performing matrix addition
print("Matrix Multiplication:\n", np.dot(matrix_a, matrix_b))  # Performing matrix multiplication
print("Element-wise Multiplication:\n", matrix_a * matrix_b)  # Performing element-wise multiplication

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
